### PR TITLE
Feature/objetivos

### PR DESCRIPTION
**Pull request by dyepes62**
**Description**
Adding component objetivos to the quienes-somos page, also moving the aliados components to a folder, like the hero component.

**Ticket trello**
https://trello.com/c/QLlvde7L/52-quienes-somos-objetivos-funcionalidad-dise%C3%B1o-sp3

**screenshots**
image
image

### CODE REVIEW

**Review by coding-tomato — COMMENTED** [review]
Is it intended for these pictures to not retain their aspect ratio? Don't know if it's a requirement.

image

**Comment by SinuheM** [comment]
Spanglish detected, maybe you can use Target instead of Objectivos

**Comment by dyepes62** [comment]
#

> Spanglish detected, maybe you can use Target instead of Objectivos

Fixed

**Comment by dyepes62** [comment]
> Is it intended for these pictures to not retain their aspect ratio? Don't know if it's a requirement.
> 
> image
Done!
image

**Review by coding-tomato — APPROVED** [review]
Looks good!

**Review by SinuheM — APPROVED** [review]
Cool

**Pull request merged**
